name: My first Workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v5
          
          - name: List files
            run: ls
          - name: Executing Shell Script
            run: |
              chmod +x ascii-script.sh
                ./ascii-script.sh
 
          #- name: List files
           # run: ls
          #- name: Show README
           # run: cat README.md